
-- Project: Retail Sales Analysis
-- File: 2_analysis.sql

-- Description:
-- This file contains exploratory and business analysis queries
-- to understand sales performance, customer behavior,
-- product trends, and time-based insights.

-- Key Analysis:
-- - Sales trends (daily, monthly)
-- - Category performance
-- - Customer analysis
-- - Gender-based insights
-- - Sales efficiency
-- - Time-based sales patterns

-- Author: Abhay Goral
-- =========================================


-- DATA EXPLORATION 
-- How many sales we have?
SELECT COUNT(*) AS total_sales FROM retail_sales

--How many unique customers we have
SELECT COUNT(DISTINCT customer_id) as unique_customers FROM retail_sales

--Unique categories
SELECT COUNT(DISTINCT category) AS unique_categories
FROM retail_sales


--DATA ANALYSIS & Business Key Problems and Answers
SELECT * FROM retail_sales

--1.SALES PERFORMANCE ANALYSIS

--What is the total revenue generated by the company?
SELECT SUM(total_sale) AS total_revenue 
FROM retail_sales;

--How do sales change day by day?
SELECT sale_date,SUM(total_sale) AS total_revenue 
FROM retail_sales
GROUP BY sale_date ORDER BY sale_date;

--Which month generated the highest revenue?
SELECT month , SUM(total_sale) AS high_revenue
FROM(
		SELECT total_sale,EXTRACT(MONTH FROM sale_date) AS month
		FROM retail_sales
	)t
GROUP BY month ORDER BY high_revenue DESC LIMIT 1;

--At what time of the day do most sales happen?
SELECT 
	CASE 
		WHEN EXTRACT(HOUR FROM sale_time) < 12 THEN 'Morning'
		WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
		ELSE 'Evening'
	END AS shifts_in_day,
	COUNT(*) AS total_transctions,
	SUM(total_sale) AS total_revenue
FROM retail_sales 
GROUP BY shifts_in_day 
ORDER BY total_revenue DESC;

--2.PRODUCT CATEGORY ANALYSIS

--Which category sells the most quantity?
SELECT category, SUM(quantity) AS category_total
FROM retail_sales
GROUP BY category
ORDER BY category_total DESC LIMIT 1;

--Which category generates highest profit?
SELECT category,
		SUM(total_sale) AS total_sales,
		ROUND(SUM(cogs)::numeric,2)  AS total_cogs,
		ROUND(SUM(total_sale-cogs)::numeric,2) AS profit
FROM retail_sales
GROUP BY category
ORDER BY profit DESC;

--What percentage of total revenue comes from each category?
SELECT category,
		SUM(total_sale) AS category_total,
		ROUND((SUM(total_sale)*100/(SELECT SUM(total_sale) FROM retail_sales))::numeric,2)
FROM retail_sales
GROUP BY category;

--3.CUSTOMER ANALYSIS
SELECT * FROM retail_sales

--Who are the top 10 customers by spending?
SELECT customer_id,
	SUM(total_sale) AS total_spent
FROM retail_sales
GROUP BY customer_id 
ORDER BY total_spent 
DESC LIMIT 10;

--Which customers purchase most frequently?
SELECT customer_id,
		COUNT(*) AS purchase_count
FROM retail_sales
GROUP BY customer_id
ORDER BY purchase_count DESC LIMIT 1;

--Which age group spends the most?
/*Age groups example:

18–25

26–35

36–45

45+ */

SELECT
	CASE
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN age BETWEEN 26 AND 35 THEN '26-35'
		WHEN age BETWEEN 36 AND 45 THEN '36-45'
		ELSE '45+'
	END AS age_group,
	SUM(total_sale) AS total_spent
FROM retail_sales
GROUP BY age_group
ORDER BY total_spent DESC;

--4.GENDER ANALYSIS

--Do male or female customers generate more revenue?
SELECT gender,SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY gender
ORDER BY total_revenue DESC;

--Which product category is preferred by each gender?
SELECT 
    gender,
    category,
    COUNT(*) AS total_purchases
FROM retail_sales
GROUP BY gender, category
ORDER BY gender, total_purchases DESC;

--5.SALES EFFICIENCY
SELECT* FROM retail_sales
--What is the average value per transaction?
SELECT COUNT(*) AS total_transaction,
		SUM(total_sale) AS total_sale,
		ROUND(AVG(total_sale)::numeric,2) AS avg_trnsaction_value
FROM retail_sales;

--How many items customers buy per purchase on average?
SELECT 
    SUM(quantity) AS total_items_sold,
    COUNT(*) AS total_transactions,
    AVG(quantity) AS avg_items_per_transaction
FROM retail_sales;


--6.TIME-BASED BUSINESS INSIGHTS

--Which day of week generates highest revenue?
SELECT 
    TO_CHAR(sale_date, 'Day') AS day_of_week,
    SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY day_of_week
ORDER BY total_revenue DESC;

--for EXACT DAY WISE
SELECT 
    TO_CHAR(sale_date, 'Day') AS day_of_week,
    EXTRACT(DOW FROM sale_date) AS day_number,
    SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY day_of_week, day_number
ORDER BY day_number;

--During which hours do customers shop most?
SELECT 
	EXTRACT(HOUR FROM sale_time) AS hours,
	COUNT(*) AS total_transactions
FROM retail_sales
GROUP BY hours
ORDER BY total_transactions DESC;